version: '3'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - bconnect-net
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./.docker/.postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    networks:
      - bconnect-net
networks:
  bconnect-net:
    driver: bridge
